arch = [
    # This :>
    "metapac",
    "yay",
    "pacman-contrib",

    # QGIS
    "qgis",
    "python-gdal",

    ## Drain
    "gmsh-bin",
    "python-shapely",
    "python-rasterio",

    "podofo",
    "cfitsio",

    # Linux things
    "linux",
    "linux-firmware",
    "linux-headers",
    "base",  # base packages
    "base-devel",  # base development packages
    # "acpi",  # battery info
    "grub",
    "os-prober",  # grub os detection
    "efibootmgr",  # efi boot manager
    "ly",  # login manager
    "intel-ucode",  # intel microcode (cpu firmware)
    "ntfs-3g",  # ntfs support
    "zram-generator",  # zram swap
    "gvfs-smb",  # smb support

    "tlp",  # battery management
    "smartmontools",  # disk health monitoring
    # "tlpui",  # battery management

    # Networking
    "networkmanager",
    "wireless_tools",
    "iwd",  # wifi
    "impala", # network manager frontend
    "network-manager-applet",
    "linux-wifi-hotspot-bin",

    "networkmanager-openvpn",  # openvpn support
    "networkmanager-l2tp",  # l2tp support (manresa vpn)
    "strongswan",  # ipsec support (manresa vpn)
    "forticlient-vpn", # fortinet vpn client (guk vpn)
    "wireguird",  # wireguard support

    # Audio
    "sof-firmware",  # sound firmware
    "wireplumber",  # audio server
    "pipewire",  # audio server
    "pipewire-alsa",
    "pipewire-jack",
    "pipewire-pulse",
    "libpulse",  # pulseaudio compatibility
    "gst-plugin-pipewire",

    # Bluetooth
    # "blueman",
    "bluez",
    "bluez-utils",
    "bluetui",

    # Utils
    "bottom",
    "brightnessctl",
    "ripgrep-all",
    "cameractrls",
    "dkms",
    "htop",
    "wget",
    "gparted",
    "nautilus",
    "neofetch",
    "vim",
    "kanata-bin",
    "imagemagick",
    "less",
    "systemctl-tui",
    "qdirstat-bin",
    "ventoy-bin",
    "7zip",
    "fzf",
    "yazi", # file manager

    # Apps
    "discord",
    "spotify-launcher",
    "spicetify-marketplace-bin", # spicetify marketplace
    # "google-chrome",
    "zen-browser-bin",
    "keepassxc",
    "gimp",
    "obsidian",
    "vlc",
    "virtualbox",
    # "nchat",
    "krita",
    "libreoffice-fresh",

    # Gaming
    "steam",
    "heroic-games-launcher-bin",
    "minecraft-launcher",
    "jre-openjdk", # java runtime for mods
    "olympus", # celeste plugin manager

    # Development
    "fish",
    "neovim",
    "visual-studio-code-bin",
    "wezterm",
    "ghostty",
    "kitty",
    "git",
    "github-cli",
    "lazygit",
    "clang",
    "mosh",
    "sshfs",
    "tmux",
    "npm",
    "yarn",
    "nodejs",
    "rustup",
    "rust-analyzer",
    "sagemath",
    "pyenv",
    "pyenv-virtualenv",
    "go",
    "dbeaver",
    "webkit2gtk", # for map preview in dbeaver
    "docker",
    "docker-compose",
    "jupyter-notebook",
    "jupyterlab-widgets",
    "valgrind",
    "typst",
    "python-jupyterlab-vim",
    "python-jupytext",
    "python-pynvim",

    # Hyprland
    "hyprland",
    "hyprpaper",
    "hyprpicker",
    "hyprshot",
    "hyprpolkitagent",
    "xdg-desktop-portal-hyprland",
    "xdg-desktop-portal-gtk",
    "rofi",
    "swaync",
    "waybar",
    "xorg-xhost", # Allow access to X server
    "uwsm",

     # Nvidia
    "nvidia-open",
    "nvidia-settings",
    "libva-nvidia-driver",
    "nvtop",
    "mesa-utils",  # glxinfo
    "gamescope",

    # Fonts
    "ttf-jetbrains-mono-nerd",
    "maplemono-nf-cn",
    "noto-fonts-emoji",

    # GTK
    "lxappearance",
    "gtk-engine-murrine",
    "kanagawa-gtk-theme-git",
    "kanagawa-icon-theme-git",
]
cargo = ["lolcrab"]

